// Per-topic authoring prompts — one focused system/instruction prompt per
// curriculum part. Lifted from the "Lesson Generation Prompts" section of
// "Clement — North Star: The Unified Path".
//
// These are the SUBJECT layer. The promptLibrary composes them with the format
// rules (author-guide.md), the teaching style (master-prompt.md), and the
// assessor persona (coach-persona.md) to build the full system prompt.
//
// Each prompt tells the author WHAT to cover. The composed system prompt tells it
// HOW (depth-to-mastery, visual-first, .lmd format).

export const TOPIC_PROMPTS: Record<number, string> = {
  0: `Teach Domain 0: what AI/ML engineers ACTUALLY do. Map the full role spectrum (Research Scientist, ML Engineer, AI Engineer, Data Scientist, MLOps/Platform) by what they really spend their days on, and where the value and difficulty live (data quality, evaluation, latency/cost, reliability, product fit). Emphasize why ~90% of the value is engineering AROUND the model, and what "discovery" really means (researcher) vs "make it reliable, cheap, shipped" (engineer). Build-to-learn seed: a one-page decision tree for "does this problem even need ML, and which role owns it?"`,

  1: `Teach Part 1: CS & Systems Foundations. Cover the memory hierarchy (stack/heap, cache lines/misses), how code actually runs (compilation vs interpretation, JIT, bytecode, GC, JVM vs CPython), concurrency & parallelism (threads/processes/async, the GIL, race conditions, deadlocks), networking (TCP/IP, HTTP, TLS handshake, DNS), OS basics (processes, virtual memory, syscalls), complexity in practice (Big-O vs constants), and the "latency numbers every engineer should know." Emphasize the design rationale: WHY these abstractions exist, why a cache miss is ~100x slower, why the GIL exists and what it trades. Build-to-learn seed: reproduce a race condition in code, then fix it three different ways and explain the trade-offs.`,

  2: `Teach Part 2: Software Design & Architecture. Cover abstraction & API design, coupling/cohesion, dependency inversion, design patterns (and when NOT to use them), SOLID, domain modeling/DDD, system design at scale (load balancing, caching, queues, statelessness), distributed systems (CAP, eventual consistency, idempotency, retries, consensus basics), and low-level vs high-level design. Emphasize taste and trade-offs: why each pattern exists and what it costs. Build-to-learn seed: redesign one module of DeskFlow or FM-AI applying these ideas, and write the design doc justifying every choice.`,

  3: `Teach Part 3: Performance & Efficiency. Cover profiling (CPU/memory/flame graphs), latency vs throughput and tail latency (p50/p99), algorithmic vs systems optimization, memory (allocation, GC pressure, cache locality), data-oriented design, batching/pipelining/backpressure, and the lower-level levers (SIMD/vectorization, why NumPy & PyTorch are fast, memory layout). Emphasize: why measuring beats guessing, and the design rationale behind vectorization. Build-to-learn seed: take a slow Python loop, profile it, vectorize it with NumPy, measure the speedup, and explain mechanically WHY it got faster.`,

  4: `Teach Part 4: Databases, deep. Cover storage & indexes (B-trees vs LSM-trees, how an index speeds a query, write amplification), query planning (EXPLAIN, N+1), transactions & ACID (isolation levels, MVCC, locking, deadlocks), normalization vs denormalization, scaling (replication, sharding, pooling, CAP in practice), SQL vs NoSQL vs NewSQL, vector databases (HNSW/IVF, similarity search for RAG), and caching/invalidation. Emphasize design rationale: WHY MVCC, WHY B-trees, why storage engines make the choices they do. Build-to-learn seed: design the schema + indexes for one of my apps, run EXPLAIN on its hot queries, OR implement a tiny B-tree from scratch.`,

  5: `Teach Part 5: Security. Cover threat modeling (STRIDE, attacker mindset), the OWASP Top 10, authN vs authZ (sessions, OAuth2/OIDC, JWT pitfalls, RBAC/ABAC), cryptography fundamentals (hashing vs encryption, salting with bcrypt/argon2, symmetric vs asymmetric, TLS, why never roll your own), secrets management, supply-chain security, defense in depth & least privilege, and AI-specific security (direct & indirect prompt injection, data poisoning, the "lethal trifecta," guardrails). Emphasize the adversarial mindset and design rationale. Build-to-learn seed: threat-model FM-AI's agent tool-calling and design concrete guardrails against indirect prompt injection.`,

  6: `Teach Part 6: ML/DL Math & Theory, math-first and derived from scratch. Cover linear algebra (eigenvalues, SVD, why everything is matrix multiplication), calculus (gradients, chain rule, Jacobians), probability & statistics (Bayes, MLE/MAP), optimization (SGD/momentum/Adam, convex vs non-convex, loss landscapes), information theory (entropy, cross-entropy, KL divergence), generalization (bias-variance, regularization, inductive bias), and architectures conceptually (MLP -> CNN -> RNN/LSTM -> Transformer -> diffusion). Emphasize the "why": why attention beat recurrence, why depth helps, what a model is actually learning. Derive, don't assert. Build-to-learn seed: derive backprop by hand, then implement it Stage 1 (scratch) -> Stage 2 (NumPy).`,

  7: `Teach Part 7: PyTorch & Deep-Learning Engineering. Core: tensors deeply (dtypes, devices, strides, views vs copies, broadcasting, contiguous memory), autograd internals (the dynamic computation graph, autograd-as-a-tape, how .backward() walks it, custom autograd.Function), nn.Module, training-loop mastery, and the Dataset/DataLoader pipeline. Advanced: debugging training (exploding/vanishing gradients, NaNs), mixed precision, distributed training (DDP/FSDP, parallelism, NCCL), performance (torch.profiler, torch.compile/TorchInductor, Triton), the dispatcher/ATen/CUDA path, and inference optimization (quantization, pruning, distillation, ONNX, KV-cache). Emphasize above all WHY PyTorch is designed the way it is (eager execution, the dispatcher, autograd-as-tape) and what each choice trades away. Build-to-learn seed: build a micro-autograd engine from scratch, then map each piece to how real PyTorch does it.`,

  8: `Teach Part 8: Applied AI / LLM Engineering. Cover prompt engineering as a discipline, RAG done right (chunking, embeddings, retrieval, re-ranking, hybrid search, and evaluating retrieval separately from generation), agentic systems (tool calling, planning, memory, multi-agent orchestration, the recursion/parse loop, self-correction), fine-tuning vs RAG vs prompting (LoRA/QLoRA, PEFT), evaluation & observability (eval sets, LLM-as-judge, regression testing, tracing), inference infrastructure (serving, batching, KV cache, vLLM, cost/latency), and guardrails. Emphasize that reliability and evaluation are the genuinely hard parts, and the design rationale of RAG vs fine-tuning. Build-to-learn seed: design and add a rigorous eval harness to EnterpriseAI's RAG, or a reliability test suite for FM-AI's agents.`,

  9: `Teach Part 9: MLOps & Production ML. Cover reproducibility (experiment tracking, seeds, data + model versioning), deployment patterns (batch vs real-time, REST/gRPC, shadow/canary/blue-green), monitoring (data drift, concept drift, model decay, alerting), CI/CD for ML, containerization & infra (Docker, Kubernetes basics, one cloud, serverless inference), and data engineering basics (ETL/ELT, feature stores, streaming vs batch). Emphasize WHY most ML projects die in production and why reproducibility is non-negotiable. Build-to-learn seed: containerize one model/feature and wire up basic drift monitoring.`,

  10: `Teach Part 10: the Meta-skills that separate top engineers. Cover debugging as a science (hypothesis -> experiment -> bisect), reading source code & papers, knowing what NOT to build (scoping, saying no), technical writing & communication (design docs, clear PRs), taste & judgment, and directing AI well (context, fundamentals, verification loops, critical review of output). Emphasize how each compounds over a career and how to deliberately practice it. Build-to-learn seed: pick one paper and reimplement it, then write the design doc for a real feature as if for review.`,

  11: `Teach Part 11: Vision & Multimodal AI. Cover how a VLM actually sees (vision encoder -> patch embeddings -> projection into the LLM token space -> decoding; the three architectural eras), vision encoders deeply (ViT/CLIP/SigLIP, patches, why resolution & patch size bound what's perceivable), the OCR vs captioning vs grounding split, lightweight local VLMs (Florence-2, Moondream, SmolVLM, Qwen2.5-VL) and matching model to task/VRAM, the "measure don't ask" principle (compute colors, contrast, gradients, spacing, and layout deterministically; reserve the VLM for semantic + aesthetic synthesis), and the accuracy/efficiency levers in detail: input resolution & tiling, quantization per pass, constrained/guided decoding (GBNF/JSON schema), decoding params, task decomposition + caching, rubric injection, and cross-check verification. Emphasize WHY each lever moves accuracy or cost, and that the model is commodity while the pipeline is the real engineering. Build-to-learn seed: build the hybrid visual-critique pipeline for DeskFlow on my 6GB RTX 4050 — deterministic CV metrics first, then a local VLM synthesis pass.`,

  12: `Teach Part 12: Training, Fine-Tuning & Model Adaptation, framed as a spectrum from heaviest to lightest intervention (pretraining -> full fine-tuning -> PEFT -> inference-time steering -> prompting/RAG). Cover what training actually is and its memory cost (weights + gradients + optimizer states + activations), hyperparameters & tuning (learning rate, batch size, schedulers, weight decay; grid/random/Bayesian search, Optuna), PEFT in depth (LoRA/QLoRA math of low-rank updates, adapters, prefix/prompt tuning) and why QLoRA is feasible on a 6GB GPU, memory-saving tricks (gradient checkpointing/accumulation, mixed precision, 4-bit base), model compression & editing (quantization PTQ/QAT, pruning, knowledge distillation, merging), data as the real bottleneck, inference-time steering with no training, and evaluation pitfalls (overfitting, catastrophic forgetting, when NOT to fine-tune). Emphasize what is actually possible on a limited device and the highest-ROI lever for each goal. Build-to-learn seed: QLoRA-fine-tune a small model (or distill/quantize one) on my RTX 4050 for a narrow task, and measure whether it actually beat a prompt+RAG baseline.`,
};

export function getTopicPrompt(part: number): string | undefined {
  return TOPIC_PROMPTS[part];
}
