import { promises as fs, watch, FSWatcher } from 'fs';
import path from 'path';

interface SpokeSummary {
  sessionId: string;
  agentType: string;
  terminalId: string;
  currentCycle: number;
  status: string;
  currentFocus: string;
  lastSeen: string;
  updatedAt: string;
}

export class StateCoordinator {
  private stateDir: string;
  private hubPath: string;
  private watcher: FSWatcher | null = null;
  private debounceTimer: NodeJS.Timeout | null = null;

  constructor(agentDir: string = 'agent') {
    this.stateDir = path.join(agentDir, 'state');
    this.hubPath = path.join(agentDir, 'state.md');
  }

  async initialize(): Promise<void> {
    await fs.mkdir(this.stateDir, { recursive: true });
    await this.regenerateHub();
    this.startWatching();
  }

  private startWatching(): void {
    try {
      this.watcher = watch(this.stateDir, (eventType, filename) => {
        if (!filename || filename.startsWith('_') || !filename.endsWith('.md')) return;
        if (this.debounceTimer) clearTimeout(this.debounceTimer);
        this.debounceTimer = setTimeout(() => this.regenerateHub(), 500);
      });
    } catch {}
  }

  async regenerateHub(): Promise<void> {
    try {
      const files = await fs.readdir(this.stateDir);
      const spokeFiles = files.filter(f => f.endsWith('.md') && !f.startsWith('_'));
      const summaries: SpokeSummary[] = [];

      for (const file of spokeFiles) {
        try {
          const content = await fs.readFile(path.join(this.stateDir, file), 'utf-8');
          const summary = this.parseSpoke(content);
          if (summary) summaries.push(summary);
        } catch {}
      }

      const hubContent = this.generateHubContent(summaries);
      await this.writeFileAtomic(this.hubPath, hubContent);
    } catch {}
  }

  private parseSpoke(content: string): SpokeSummary | null {
    const sessionMatch = content.match(/<!-- SESSION: (.+) -->/);
    const agentMatch = content.match(/<!-- AGENT: (.+?) \|/);
    const terminalMatch = content.match(/<!-- AGENT: .+ \| TERMINAL: (.+?) \|/);
    const cycleMatch = content.match(/## CURRENT CYCLE \((\d+)\)/);
    const roleMatch = content.match(/\*\*ROLE:\*\* (.+)/);
    const updatedMatch = content.match(/\*\*UPDATED:\*\* (.+)/);

    if (!sessionMatch || !cycleMatch) return null;

    const updatedAt = updatedMatch ? updatedMatch[1] : new Date().toISOString();
    const date = new Date(updatedAt);
    const lastSeen = isNaN(date.getTime())
      ? 'unknown'
      : date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false });

    return {
      sessionId: sessionMatch[1].trim(),
      agentType: agentMatch ? agentMatch[1].trim() : 'unknown',
      terminalId: terminalMatch ? terminalMatch[1].trim() : 'unknown',
      currentCycle: parseInt(cycleMatch[1]),
      status: 'active',
      currentFocus: roleMatch ? roleMatch[1].trim() : 'Unknown',
      lastSeen,
      updatedAt,
    };
  }

  private generateHubContent(summaries: SpokeSummary[]): string {
    const now = new Date().toISOString();
    const rows = summaries.map(s =>
      `| ${s.agentType} | ${s.sessionId} | ${s.currentCycle} | ${s.status} | ${s.currentFocus} | ${s.lastSeen} |`
    ).join('\n');

    const events = summaries.map(s =>
      `- \`[${s.lastSeen}]\` ${s.sessionId} → ${s.status}: ${s.currentFocus}`
    ).slice(0, 10).join('\n');

    return `# DeskFlow — Multi-Agent State Hub  (v2.0)

> **SYSTEM:** Multi-agent state v2.0 | **UPDATED:** ${now} | **GENERATED BY:** main-process

---

## YOUR SESSION
**ID:** \`{YOUR_SESSION_ID}\`
**FILE:** \`agent/state/{YOUR_SESSION_ID}.md\`
> Read YOUR file for full history. Write to it at cycle end. NEVER edit this hub.

---

## ACTIVE AGENTS (${summaries.length})

| AGENT | SESSION | CYCLE | STATUS | FOCUS | LAST SEEN |
|-------|---------|-------|--------|-------|-----------|
${rows || '| (none) | — | — | — | — | — |'}

---

## RECENT EVENTS (last 10)
${events || '- (no events yet)'}

---

## PROTOCOL — READ CAREFULLY
1. **READ:** Your spoke file (\`agent/state/{YOUR_SESSION}.md\`) for full history
2. **WRITE:** Overwrite your spoke file at cycle end (keep latest 3 cycles)
3. **NEVER** write to this hub file — it is auto-generated by the main process
4. **CROSS-AGENT:** Read other spoke files if you need details on their work
5. **FORMAT:** Follow \`agent/state/_template.md\` exactly
6. **SESSION ID:** Check \`DESKFLOW_SESSION_ID\` env var, or derive from \`{agentType}-{terminalId.slice(0,6)}-{entropy}\`
`;
  }

  private async writeFileAtomic(filePath: string, content: string): Promise<void> {
    const tempPath = `${filePath}.tmp.${Date.now()}`;
    await fs.writeFile(tempPath, content, 'utf-8');
    await fs.rename(tempPath, filePath);
  }

  dispose(): void {
    if (this.watcher) { this.watcher.close(); this.watcher = null; }
    if (this.debounceTimer) { clearTimeout(this.debounceTimer); this.debounceTimer = null; }
  }
}
