/* Barrel exports for the v3.1 neon cyberpunk cityscape (radial metropolis). */
export { CityScene } from './CityScene'
export type { CitySceneProps } from './CityScene'
export { generateMetropolis } from './metropolis'
export type { HeroInput, Tower, Lane, Metropolis } from './metropolis'
export { toHeroes, AGENT_COLORS } from './dataAdapter'
export type { ByToolRow } from './dataAdapter'
export { PALETTE, NEON_RAMP } from './palette'
export { Ground } from './Ground'
export { SkyDome } from './SkyDome'
export { InstancedSkyline } from './InstancedSkyline'
export { HeroOverlays } from './HeroOverlays'
export { CityCars } from './CityCars'
export { CityLighting } from './CityLighting'
export { CityPostFX } from './CityPostFX'
export { StatsPanel } from './StatsPanel'
